<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Infinity" name="firstHomeWork.LoginTest" tests="5" failures="0" timestamp="25 Oct 2017 18:07:11 GMT" time="28.122" errors="1">
  <testcase name="testIncorrectDataForLogging" time="2.930" classname="firstHomeWork.LoginTest"/>
  <testcase name="testIncorrectDataForLogging" time="2.990" classname="firstHomeWork.LoginTest">
    <error type="java.lang.AssertionError" message="
Expected: a string containing &quot;ÍÅÂÅÐÍÛÉ ÏÀÐÎËÜ&quot;
     but: was &quot;ÒÀÊÎÃÎ ÐÀÁÎÒÍÈÊÀ ÍÅÒ ÈËÈ ÏÀÐÎËÜ ÓÊÀÇÀÍ ÍÅÂÅÐÍÎ.&quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "ÍÅÂÅÐÍÛÉ ÏÀÐÎËÜ"
     but: was "ÒÀÊÎÃÎ ÐÀÁÎÒÍÈÊÀ ÍÅÒ ÈËÈ ÏÀÐÎËÜ ÓÊÀÇÀÍ ÍÅÂÅÐÍÎ."
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
	at utilsAndHelpers.HelpersMethod.assertContains(HelpersMethod.java:100)
	at firstHomeWork.LoginMethod.testIncorrectDataForLogging(LoginMethod.java:36)
	at firstHomeWork.LoginTest.testIncorrectDataForLogging(LoginTest.java:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:373)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:334)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:119)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:407)
]]>
    </error>
  </testcase> <!-- testIncorrectDataForLogging -->
  <testcase name="loginTest" time="8.449" classname="firstHomeWork.LoginTest"/>
  <testcase name="loginTest" time="6.664" classname="firstHomeWork.LoginTest"/>
  <testcase name="loginTest" time="7.089" classname="firstHomeWork.LoginTest"/>
</testsuite> <!-- firstHomeWork.LoginTest -->
